# Copy to config/config.yaml for local dev
MAX_PRODUCTS: 15
DEV_MODE: False
RECORD_CACHE: False
USE_CACHE: true

DB_PATH: data/styletelling.sqlite
CACHE_DIR: data/cached_queries_v1
PROMPT_DIR: prompts

PAGE_TITLE: "Styletelling"
PAGE_ICON: "✨"
LAYOUT: "wide"

# API keys
API_KEY: "***"
# OPENAI_API_KEY: "***"
# GROQ_API_KEY: "***"
# DEEPSEEK_API_KEY: "***"
# GEMINI_API_KEY: "***"
